#cloud-config
users:
  - name: ubuntu
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash

runcmd:
  - apt update
  - apt upgrade
  - apt install nginx -y
  - systemctl enable nginx
  - systemctl start nginx